language: clojure
notifications:
  email:
    on_success: never
  slack:
    secure: JneD1oljOy6OKgWVzsQAniLASJSqQ9Gp/5bwPBmCstiCpdA+fKuYkVL9oAyH7lFrPwDkkQwLCHkJT3Css/rdUSUH78hXufYiIdt0X3yMFtWOJTD4o3i9cpFGmC+0VO1kH6b+D47d9Y0+GJUTj5UGDrnLhZMFfI9AQbhJt0uLwHZqFj5lRtepP4ijXN2i+Yth4DD5MlVsY8uuiY4RcWhATzQW24EhFmfLqCHnSZs9wdw1SWYbvic3ij14dxSu1TK+8LuavpjMI8KqsKg6o2NGp5Iq5h4qnK5NycZmqmh1N6JEXslDLWk3BYPjAIZBBncTLThiC3ghjGwoS110Ow/mF6ELPNsaWgai8blMllEP0o9ZwMqV9gJrOy5hLsa7b72u+CTJLETFHNELPWjR3mocTl9rVJpseXI3vfgEM5LlBhedL1E0+SzHNLOfVtDe+5v1rl4UFQEqu8yd2Z0+T4mWjCj01LmudFymXoRusUxsNG7L/ocSqOTYyB5i14QzQe+XxnMyG6rCKEdlXzFciJwv6xvzl6W9YWIXuApVHaTRGBUyQsjsPPnDhNqG51ZiCrbQ31/vlbbY9FhmeTnlEVEfGvDqnIxQJmSudspr4kJft43qQHdFiNSnOtr9SVb4y79Ef8ntmWhGFs445ydae2a1MZjEXpdp6Bg0r9l2wVWN4AM=
